### ISSUE TITLE
issue with PE 2016.4 and version 3.x

### ISSUE THREAD

**Issue by dannygoulder** [waveclaw/puppet-subscription_manager#48]
When updating to the 3.x module all nodes (with the exception of the master) fail to apply the catalog as follows:

```
Error: Could not autoload puppet/feature/json: undefined method `feature' for Puppet:Module
Error: Failed to apply catalog: Could not autoload puppet/feature/json: undefined method `feature' for Puppet:Module
```

Thinking that something has changed for Puppet 4 support in `lib/puppet/feature/json.rb`, and has caused this to occur, not sure if pluginsync is broken (the `json.rb` file is definitely present on the node in `/opt/puppetlabs/puppet/cache`).

Running the agent with `--debug` doesn't yield much extra info.

Please let me know if any more info is required

**Comment by waveclaw** [comment]
This is due to a very old check back from Puppet 2.7.x.

For examples of how to confine features you have to examine the actual Puppet codebase.

https://github.com/puppetlabs/puppet/blob/master/lib/puppet/feature/base.rb

This passes my test suite on 2016.4.1.  But I have not tested the 2016.4.0 since upgrade to 3.0.x.

Looking at the alternatives:

```ruby
Puppet.features.add(:json, :libs => ["json"]) unless Puppet.features.json?
```
and how Puppet Labs doesn't bother to check, I'm inclined to accept the merge and update.   You will be added to the contributors and expected to accept the license for distribution of changes, of course.

**Comment by waveclaw** [comment]
Accepted the fix; tests pass.

**Comment by dannygoulder** [comment]
Great, and thanks for the instant release!  Fine with the distribution license (do I need to click anything?)

**Comment by waveclaw** [comment]
Nope.  Just saying you are fine with it is more than most people give.  Thank you for the contribution, every little fix helps.
